  # tasks:
  # - name: GET WORKER NODE DETAILS
  #   community.kubernetes.k8s_info:
  #     kind: Node
  #     namespace: default
  #   register: node_result

  # - name: DISPLAY OUTPUT
  #   debug:
  #     msg: "{{ node_result }}"

---
- name: Kubernetes Worker Node Details
  hosts: k8s_workers
  tasks:
    - name: GET WORKER NODE DETAILS
      community.kubernetes.k8s_info:
        kubeconfig: /home/teeadmin/.kube/config
        api_version: v1
        kind: Node
        namespace: default
      register: node_info

    - name: Show worker node details
      debug:
        var: node_info
